# Graphite backend address
graphite_addr = "localhost:2003"

# Port to listen for statsd messages from clients over UDP
port = 8125

# Print some verbose debugging information
debug = true

# Interval to flush to graphite in milliseconds
flush_interval_ms = 2000

# Dot-separated namespace for metrics. %H will be replaced with the machine's hostname. For instance, if
# namespace is example.%H and the hostname is web-25, then a counter called web.requests would be sent to
# graphite with the name "example.web-25.counters.web.requests".
namespace = "example.%H"

# Whether to send back some counters about the stats that gost has seen (for instance, the number of bad
# messages and the number of packets received).
meta_stats = true

# The os_stats section specifies stats that gost will determine from the host system.
# NOTE: These stats are linux-specific. They pull information from the /proc filesystem.
# NOTE: Delete/comment out the whole os_stats section if you're not using it.
[os_stats]

# check_interval_ms is used to change the frequency OS stat checks are done. If not given, the checks will be
# performed every flush_interval_ms.
check_interval_ms = 30000

# load_avg and load_avg_per_cpu return the 1/5/15 minute load averages; the latter divides the numbers by the
# number of logical CPUs to normalize them.
# NOTE: The valid values are obviously 1, 5, and 15 only.
load_avg = [1, 5, 15]
load_avg_per_cpu = [1, 5, 15]

# A disk_usage section generates a gauge for how much space is used on a particular volume.

# In this example, the gauge is called 'data_volume', it monitors /mnt/data, and the gauge is the absolute
# amount of space used (in bytes). If "fraction" is used instead, it will report the fraction of the total
# used (0.0 - 1.0).
[os_stats.disk_usage.data_volume]
path = "/mnt"
values = "fraction"
