# Graphite backend address
graphite_addr = "localhost:2003"

# Gost forwarding address -- if this variable is set, forwarding to another gost is enabled
forwarding_addr = "localhost:8124"

# Bind address to listen on for forwarded messages -- if this is set, gost is configured as a forwarder
forwarder_listen_addr = ":8124"

# Namespace for forwarded stats. This variable must be set if forwarder_listen_addr is set.
forwarded_namespace = "example.global"

# Port to listen (on localhost) for statsd messages from clients over UDP
port = 8125

# Port to listen (on localhost) for people to connect (using, e.g., telnet) for debugging output.
debug_port = 8126

# Print some verbose debugging information
debug_logging = true

# This option controls whether gost clears out stats after it flushes. If true, gost won't remember what stats
# it has seen; if false, it will set counts to 0 (and leave gauges at the previous value) but keep sending the
# zeroed-out values.
clear_stats_between_flushes = false

# Interval to flush to graphite in milliseconds
flush_interval_ms = 2000

# Dot-separated namespace for metrics. %H will be replaced with the machine's hostname. For instance, if
# namespace is example.%H and the hostname is web-25, then a counter called web.requests would be sent to
# graphite with the name "example.web-25.counters.web.requests".
namespace = "example.%H"

# Whether to send back some counters about the stats that gost has seen (for instance, the number of bad
# messages and the number of packets received).
meta_stats = true

# The scripts section specifies how to run auxiliary scripts. This section should be removed or commented out
# if no scripts are going to be used.
[scripts]

# This is a directory where scripts are located. If a relative path, it is relative to the current working
# directory of the gost process.
path = "scripts"

# The frequency with which to run scripts. Each script is started this frequently. The next run of the script
# does not start until that script has exited, even if it misses run intervals.
run_interval_ms = 10000

# The os_stats section specifies stats that gost will determine from the host system.
# NOTE: Everything below here is linux-specific. os_stats pulls information from the /proc filesystem and
# Linux syscalls.
# NOTE: Delete/comment out the whole os_stats section if you're not using it.
[os_stats]

# check_interval_ms is used to change the frequency OS stat checks are done. If not given, the checks will be
# performed every flush_interval_ms.
#check_interval_ms = 30000

# load_avg and load_avg_per_cpu show the 1/5/15 minute load averages; the latter divides the numbers by the
# number of logical CPUs to normalize them.
#load_avg = true
load_avg_per_cpu = true

# A disk_usage section generates a gauge for how much space is used on a particular volume.

# In this example, the gauge is called 'data_volume', it monitors /mnt/data, and the gauge is the absolute
# amount of space used (in bytes). If "fraction" is used instead, it will report the fraction of the total
# used (0.0 - 1.0).
[os_stats.disk_usage.data_volume]
path = "/mnt/data"
values = "absolute"
